apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      run: frontend-demo
  template:
    metadata:
      name: frontend-pod
      labels:
        run: frontend-demo
    spec:
      containers:
        - name: frontend
          image: "us.icr.io/k8app/frontend:1" # edit here!
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    run: frontend-demo
spec:
  type: NodePort
  selector:
    run: frontend-demo
  ports:
   - protocol: TCP
     port: 8081
     nodePort: 30081
