apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      run: backend-demo
  template:
    metadata:
      name: backend-pod
      labels:
        run: backend-demo
    spec:
      containers:
        - name: backend
          image: "us.icr.io/k8app/backend:1" # edit here!
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    run: backend-demo
spec:
  type: NodePort
  selector:
    run: backend-demo
  ports:
   - protocol: TCP
     port: 8080
     name: http
