apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-tomcat
  template:
    metadata:
      labels:
        app: backend-tomcat
    spec:
      containers:
        - name: backend-tomcat
          image: "us.icr.io/k8app/backend-tomcat:3"
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-tomcat-service
spec:
  type: NodePort
  selector:
    app: backend-tomcat
  ports:
   - protocol: TCP
     port: 8080
     nodePort: 30085
